#!/usr/bin/env python
# -*- coding: utf-8 -*-
# attr_dicts.py
"""Dicts with German translations for attributes."""

german_attrs = {
    "academic_title": "Akademischer Titel",
    "age": "Alter",
    "alternative_address": "Alternative Adresse",
    "appartment_number": "Wohnungsnummer",
    "company_name": "Unternehmen",
    "date_of_birth": "Geburtsdatum",
    "date_of_death": "Todesdatum",
    "deceased": "gestorben",
    "delivery_address": "Lieferadresse",
    "delivery_instruction": "Lieferanweisung",
    "district": "Stadtteil",
    "division": "Abteilung",
    "divorcée": "geschieden",
    "first_name": "Vorname",
    "gender": "Geschlecht",
    "generational_suffix": "Generations-Suffix (z.B. 'Jr.')",
    "job_title": "Stellenbezeichnung",
    "last_name": "Nachname",
    "maiden_name": "Geburtsname",
    "main_phone_number": "Haupttelefonnummer",
    "middle_names": "weitere Vornamen",
    "name_of_building": "Gebäudenamen",
    "name_of_company": "Unternehmensname",
    "name_of_institution": "Institutionsname",
    "name_of_public_authority": "Behördenname",
    "province": "Bundesland",
    "nickname": "Spitzname",
    "peer_preposition": "Adelsprädikat",
    "peer_title": "Adelstitel",
    "phone_extension": "Durchwahl",
    "profession": "Beruf",
    "room_number": "Zimmernummer",
    "salutation": "Anrede",
    "stairs": "Stiegen",
    "state": "Land",
    "street": "Straße",
    "street_number": "Hausnummer",
    "sublodging": "c/o",
    "ward": "Wahlkreis",
    "year_of_birth": "Geburtsjahr",
    "year_of_death": "Todesjahr",
    "zip_code": "Postleitzahl",
}
